### ISSUE TITLE
Взаимодействие с кошельком при создании аренды

### ISSUE THREAD

**Issue by DenVot** [hsse-tech/hsse-tech-backend#5]

**Comment by FismanMaxim** [comment]
Создал функциональные интерфейсы [CreateRentProcessor](https://github.com/hsse-tech/hsse-tech-backend/blob/rent-setup/src/main/java/com/mipt/hsse/hssetechbackend/rent/RentProcessing/CreateRentProcessing/CreateRentProcessor.java) и [DeleteRentProcessor](https://github.com/hsse-tech/hsse-tech-backend/blob/rent-setup/src/main/java/com/mipt/hsse/hssetechbackend/rent/RentProcessing/DeleteRentProcessing/DeleteRentProcessor.java) в https://github.com/hsse-tech/hsse-tech-backend/pull/7.

RentService содержит список экземпляров реализаций этих интерфейсов и запускает их при создании и удалении аренды соответственно.

Порядок запуска реализаций, вообще, не определен, но они запускаются в одной транзакции. Выброс исключения хотя бы одной из реализаций приводит к rollback'у всей транзакции. 

Гарантируется, что все реализации будут выполнены до создания или удаления аренды (т.е. записи/удаления в таблицу rent).
