### ISSUE TITLE
Домен для QR-кода должен получаться из props

### ISSUE THREAD

**Issue by DenVot** [hsse-tech/hsse-tech-backend#57]

**Comment by FismanMaxim** [comment]
https://github.com/hsse-tech/hsse-tech-backend/pull/59, но qr код пока отменяем

**Comment by FismanMaxim** [comment]
Дальнейшая судьба qr-кода не особо понятна (особенно учитывая переход на пассивный замок). Возможно, он будет не нужен. Так что я это пока закрою. Сама система qr-кодов сейчас находится в нерабочем, наполовину закомментированном состоянии.
